### ISSUE TITLE
Can `model` & `residual` take a list?

### ISSUE THREAD

**Issue by Athanaseus** [landmanbester/spimple#10]
Currently `model` & `residual` takes a cube, but one needs to specify per-channel weights to use during fit to the frequency axis.

command: `spi-fitter -model model_cube.fits -residual residual_cube.fits -o alpha -th 10 -ncpu 32 -pb-min 0.15 -cw 0.43 1 0.6 0.35 0.95 0.86 0.37 0.36 -acr -bm JimBeam -band l`

It will also be nice to have the `model` & `residual` take a list of files (model list).

command: `spi-fitter -model model_1.fits model_2.fits model_3.fits model_4.fits -residual residual_1.fits  residual_2.fits residual_3.fits residual_4.fits -o alpha -th 10 -ncpu 32 -pb-min 0.15 -acr -bm JimBeam -band l`

This should also allow overriding the header weights with the command line specified weights: ` -cw 0.43 1 0.6 0.35`

**Comment by landmanbester** [comment]
@Athanaseus I will be very grateful if you can implement something like this because it would avoid the stacking step. The WSUM entries in the headers actually gets lost during this process which is why you need to specify the channel weights manually
