### ISSUE TITLE
TypeError when using -cp with the imconv task

### ISSUE THREAD

**Issue by francescaLoi** [landmanbester/spimple#5]
Hey @landmanbester ,
this command:
`spimple-imconv -image mfs07/output/continuum/polarization/test3_fast_mfs07-Q-image.fits -o test -pp 0.008333333 0.008333333 0 -nthreads 10 -cp`

failed with this error:
```
INFO      14:02:09 - IMCONV             | Input Options:
INFO      14:02:09 - IMCONV             |                          image = mfs07/output/continuum/polarization/test3_fast_mfs07-Q-image.fits
INFO      14:02:09 - IMCONV             |                output_filename = test
INFO      14:02:09 - IMCONV             |                       psf_pars = [0.008333333, 0.008333333, 0.0]
INFO      14:02:09 - IMCONV             |                       nthreads = 10
INFO      14:02:09 - IMCONV             |                       circ_psf = True
INFO      14:02:09 - IMCONV             |                     beam_model = None
INFO      14:02:09 - IMCONV             |                           band = l
INFO      14:02:09 - IMCONV             |                         pb_min = 0.05
INFO      14:02:09 - IMCONV             |                   padding_frac = 0.5
INFO      14:02:09 - IMCONV             |                      out_dtype = f4
Traceback (most recent call last):
  File "/home/floi/.local/bin/spimple-imconv", line 8, in <module>
    sys.exit(image_convolver())
  File "/home/floi/.local/lib/python3.8/site-packages/spimple/apps/image_convolver.py", line 104, in image_convolver
    gaussparf[0] = e
TypeError: 'tuple' object does not support item assignment
```

**Comment by landmanbester** [comment]
It should be fixed in the imconv-fixes branch. I'm also looking into an issue where high frequency ripples sometimes get introduced during the convolution. I'm pretty sure this is new as I've not noticed it before. I'll make a new release when I get to the bottom of it

**Comment by landmanbester** [comment]
There were some precision issues that could have resulted in unstable behaviour. Should all be fixed in the imconv-fixes branch. @Mulan-94 can you give it a go with the latest changes? You should not have to set -cp anymore, worked for me anyway. If this works I'll get a new release out tomorrow

**Comment by Mulan-94** [comment]
@landmanbester Yes, it works very well now for me, those two problematic channels I had with my cube have disappeared as well. Both with and without `-cp`
